# Custom Layer

## Layers without Parameters

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X-X.mean()

In [5]:
layer = CenteredLayer()
layer(torch.Tensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
net = nn.Sequential(nn.Linear(8, 16), CenteredLayer())
net

Sequential(
  (0): Linear(in_features=8, out_features=16, bias=True)
  (1): CenteredLayer()
)

In [11]:
Y = net(torch.rand(1,8))
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

## Layers with Parameters

In [13]:
class MyLinear(nn.Module):
    def __init__(self,input,output):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(input,output))
        self.bias = nn.Parameter(torch.rand(output))

    def forward(self, X):
        return F.relu(torch.mm(X,self.weight)+self.bias)


In [15]:
dense = MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[0.7177, 0.4595, 0.5840],
        [0.6388, 0.8264, 0.8702],
        [0.5735, 0.0118, 0.3865],
        [0.8841, 0.3889, 0.1103],
        [0.3157, 0.0599, 0.5525]], requires_grad=True)

In [16]:
dense(torch.rand(1,5))

tensor([[1.5787, 1.2724, 1.1200]], grad_fn=<ReluBackward0>)

In [19]:
net = nn.Sequential(MyLinear(64,8),nn.ReLU(), MyLinear(8,1))
net(torch.rand(2,64))

tensor([[46.5474],
        [50.3859]], grad_fn=<ReluBackward0>)