# GPUs

In [1]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda')

(device(type='cpu'), <torch.cuda.device at 0x1f6daeb9520>)

In [2]:
torch.cuda.device_count()

1

In [3]:
def try_gpu(i=0):  #@save
    """Return gpu(i) if exists, otherwise return cpu()."""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """Return all available GPUs, or [cpu(),] if no GPU exists."""
    devices = [
        torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [8]:
torch.device('cuda')

device(type='cuda')

## Tensors and GPUs

In [5]:
x = torch.rand(2,3)
x.device

device(type='cpu')

### Storage on the GPU

In [7]:
X = torch.ones((2,3), device= try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

### Copying

In [9]:
Y = torch.rand((2,3), device=torch.device('cpu'))
Z = Y.cuda(0)
Y,Z

(tensor([[0.5044, 0.6107, 0.9152],
         [0.5963, 0.0152, 0.8250]]),
 tensor([[0.5044, 0.6107, 0.9152],
         [0.5963, 0.0152, 0.8250]], device='cuda:0'))

In [11]:
X+Z

tensor([[1.5044, 1.6107, 1.9152],
        [1.5963, 1.0152, 1.8250]], device='cuda:0')

## Neural Networks and GPUs

In [12]:
net = nn.Sequential(nn.Linear(3,1))
net = net.to(device=torch.device('cuda'))

In [13]:
net(X)

tensor([[0.7774],
        [0.7774]], device='cuda:0', grad_fn=<AddmmBackward>)

In [14]:
net[0].weight.data.device

device(type='cuda', index=0)

In [18]:
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)
c = a.cuda()
d = b.cuda()

In [19]:
torch.mm(a,b)

tensor([[2481.7397, 2481.9324, 2497.2939,  ..., 2483.4275, 2477.1274,
         2518.6218],
        [2486.5198, 2507.1538, 2521.2373,  ..., 2495.8093, 2486.5549,
         2537.0662],
        [2486.8848, 2486.8499, 2501.4480,  ..., 2470.7163, 2478.9766,
         2511.6184],
        ...,
        [2462.7896, 2475.8093, 2513.0396,  ..., 2483.8140, 2473.3503,
         2512.2256],
        [2500.4404, 2499.7024, 2524.7837,  ..., 2521.6809, 2507.0811,
         2545.5786],
        [2463.9336, 2491.6150, 2501.5088,  ..., 2488.1877, 2481.8447,
         2506.7900]])

In [21]:
torch.mm(c,d)

tensor([[2481.7415, 2481.9312, 2497.2910,  ..., 2483.4246, 2477.1252,
         2518.6218],
        [2486.5132, 2507.1541, 2521.2378,  ..., 2495.8098, 2486.5542,
         2537.0640],
        [2486.8840, 2486.8499, 2501.4517,  ..., 2470.7119, 2478.9736,
         2511.6262],
        ...,
        [2462.7922, 2475.8096, 2513.0398,  ..., 2483.8115, 2473.3455,
         2512.2300],
        [2500.4443, 2499.7056, 2524.7827,  ..., 2521.6807, 2507.0793,
         2545.5791],
        [2463.9331, 2491.6121, 2501.5088,  ..., 2488.1863, 2481.8420,
         2506.7939]], device='cuda:0')